
name: Deploy en DS

on:
  workflow_call:
    inputs:
      deploy_dir:
        required: true
        type: string
        description: carpeta donde se va a actualizar el código
      exclusiones:
        required: false
        type: string
        default: ','
        description: elementos no trackeados que no deben ser borrados si existen en deploy_dir, separados por coma y sin espacios

jobs:
  deploy:
    # como es público y usa runners en nuestro servidor no queremos que lo pueda correr cualquiera
    # requerimos también que la ruta de deploy sea absoluta
    if: (github.repository_owner == 'scanntech') && (startsWith(inputs.deploy_dir, '/'))

    runs-on: [self-hosted, ds]

    steps:
      - uses: actions/checkout@v2
      - name: copiar a carpeta deploy
        # Opciones de rsync:
        # -v verbose
        # -h human readable
        # -c decide que sincronizar según checksum en vez de mod-time y size
        # -r recursivo
        # -l symlinks tratados como symlinks (si apunta a una carpeta no sincroniza sus contenidos)
        # -H mantiene hardlinks
        # --delete borra lo que sobre en el destino
        # --exclude ignora para mandar *y* para borrar en el destino
        run: |
          mkdir -p ${{ inputs.deploy_dir }}
          rsync -vhcrlH --delete --exclude=.git/ --exclude={${{ inputs.exclusiones }}} . ${{ inputs.deploy_dir }}
